feat: 修复构建及启动参数错误

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -25,20 +25,20 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Free disk space
-        if: matrix.platform == 'linux/amd64'
-        run: |
-          echo "Initial disk usage:"
-          df -h
-          # sudo rm -rf /usr/local/lib/android
-          # sudo rm -rf /usr/share/dotnet
-          # sudo rm -rf /opt/ghc
-          # sudo rm -rf /opt/hostedtoolcache/CodeQL
-          docker system prune -af || true
-          sudo apt-get clean
-          sudo apt-get autoremove -y
-          echo "Disk usage after cleanup:"
-          df -h
+      # - name: Free disk space
+      #   if: matrix.platform == 'linux/amd64'
+      #   run: |
+      #     echo "Initial disk usage:"
+      #     df -h
+      #     # sudo rm -rf /usr/local/lib/android
+      #     # sudo rm -rf /usr/share/dotnet
+      #     # sudo rm -rf /opt/ghc
+      #     # sudo rm -rf /opt/hostedtoolcache/CodeQL
+      #     docker system prune -af || true
+      #     sudo apt-get clean
+      #     sudo apt-get autoremove -y
+      #     echo "Disk usage after cleanup:"
+      #     df -h
 
       - name: Docker metadata
         id: meta
